name: Run QA Tests

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout QA repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run tests
        run: pytest --alluredir=allure-results

      - name: Generate Allure report
        run: allure generate allure-results -o allure-report --clean
