name: Run QA Tests and Publish Report

on:
  workflow_dispatch:

permissions:
  contents: write  # Necesario para hacer push a gh-pages

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout QA repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run tests
        run: pytest --alluredir=allure-results || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

  deploy-report:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout QA repo
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Allure CLI via npm
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        run: allure generate allure-results -o allure-report --clean

      - name: Copy report to deployment folder
        run: |
          mkdir -p public
          cp -r allure-report/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

      - name: Add link to report in summary
        run: echo "🔗 Ver reporte de Allure" >> $GITHUB_STEP_SUMMARY
